/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/AppLoading.vue')['default']
    Chart: typeof import('./../components/Chart.vue')['default']
    DefaultChart: typeof import('./../components/Chart/DefaultChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconLock: typeof import('@element-plus/icons-vue')['Lock']
    ElIconSwitchButton: typeof import('@element-plus/icons-vue')['SwitchButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Keyboards: typeof import('./../components/Keyboards.vue')['default']
    MapChart: typeof import('./../components/Chart/MapChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiDatePicker: typeof import('./../components/UiComponents/UiDatePicker.vue')['default']
    UiInput: typeof import('./../components/UiComponents/UiInput.vue')['default']
    UiSelect: typeof import('./../components/UiComponents/UiSelect.vue')['default']
    UiTreeSelect: typeof import('./../components/UiComponents/UiTreeSelect.vue')['default']
    VueKeyborard: typeof import('./../components/VueKeyborard.vue')['default']
  }
}
